<<<<<<< HEAD
# Generated by Django 4.2.10 on 2024-03-19 19:14
=======
# Generated by Django 5.0.2 on 2024-03-19 12:46
>>>>>>> 16925ccc214be328dc51b0edac49c0b2108272f4

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
    ]
