# Generated by Django 5.0.2 on 2024-03-02 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courseListAPI', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='userID',
        ),
    ]
