# Generated by Django 5.0.3 on 2024-03-14 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseListAPI', '0001_initial'),
        ('reviews', '0007_studentenrollsincourse_is_approved_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='reviews',
            field=models.ManyToManyField(related_name='studcoursereviews', to='reviews.studentreviewcourse'),
        ),
    ]
