# Generated by Django 5.0.2 on 2024-03-19 12:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courseListAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answerText', models.CharField(max_length=50)),
                ('isAnswer', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.CharField(max_length=50)),
                ('courseDescription', models.CharField(max_length=300)),
                ('coursePrice', models.FloatField()),
                ('courseReviewScore', models.FloatField(blank=True)),
                ('courseType', models.CharField(max_length=50)),
                ('courseImage', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='course_images')),
                ('courseLessons', models.IntegerField(default=0)),
                ('courseHours', models.FloatField(default=0)),
                ('courseDate', models.DateField(default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionHead', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirementDescription', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sectionName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videoTitle', models.CharField(max_length=50)),
                ('videoDescription', models.CharField(max_length=300)),
                ('videoLink', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='WhatYoullLearn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatYoullLearnDescription', models.CharField(max_length=50)),
            ],
        ),
    ]
