# Generated by Django 5.0.3 on 2024-03-14 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseListAPI', '0002_course_reviews'),
        ('reviews', '0007_studentenrollsincourse_is_approved_approval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='reviews',
            field=models.ManyToManyField(default=None, related_name='studcoursereviews', to='reviews.studentreviewcourse'),
        ),
    ]
