<<<<<<< HEAD
# Generated by Django 4.2.10 on 2024-03-19 19:14
=======
# Generated by Django 5.0.2 on 2024-03-19 12:47
>>>>>>> 16925ccc214be328dc51b0edac49c0b2108272f4

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0002_initial'),
        ('courseListAPI', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='reviews',
            field=models.ManyToManyField(blank=True, related_name='studcoursereviews', to='reviews.studentreviewcourse'),
        ),
        migrations.AddField(
            model_name='course',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answer',
            name='questionID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courseListAPI.question'),
        ),
    ]
