# Generated by Django 5.0.2 on 2024-03-07 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courseListAPI', '0002_remove_course_userid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='courseID',
            new_name='sectionID',
        ),
    ]
