# Generated by Django 5.0.2 on 2024-03-08 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseListAPI', '0003_rename_courseid_video_sectionid'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='courseImage',
            field=models.ImageField(blank=True, default='testImage.png', null=True, upload_to='course_images'),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answerText', models.CharField(max_length=50)),
                ('isAnswer', models.BooleanField(default=False)),
                ('questionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courseListAPI.question')),
            ],
        ),
        migrations.DeleteModel(
            name='PaymentMethod',
        ),
    ]
