# Generated by Django 5.0.2 on 2024-03-13 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseListAPI', '0004_course_courseimage_answer_delete_paymentmethod'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirementDescription', models.CharField(max_length=50)),
                ('courseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courseListAPI.course')),
            ],
        ),
        migrations.CreateModel(
            name='WhatYoullLearn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatYoullLearnDescription', models.CharField(max_length=50)),
                ('courseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courseListAPI.course')),
            ],
        ),
    ]
