# Generated by Django 5.0.2 on 2024-03-10 19:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseListAPI', '0004_course_courseimage_answer_delete_paymentmethod'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='courseDate',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='courseHours',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='courseLessons',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='userID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
