# Generated by Django 5.0.2 on 2024-03-18 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courseListAPI', '0004_auto_20240318_2254'),
    ]

    operations = [
    ]
