# Generated by Django 5.0.3 on 2024-03-14 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseListAPI', '0004_alter_course_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='courseReviewScore',
            field=models.FloatField(blank=True),
        ),
    ]
