# Generated by Django 5.0.2 on 2024-03-13 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courseListAPI', '0005_requirement_whatyoulllearn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='questionAnswer',
        ),
        migrations.RemoveField(
            model_name='question',
            name='questionImage',
        ),
    ]
