# Generated by Django 5.0.2 on 2024-03-16 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseListAPI', '0005_alter_course_coursereviewscore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='questionAnswer',
        ),
        migrations.RemoveField(
            model_name='question',
            name='questionImage',
        ),
        migrations.RemoveField(
            model_name='question',
            name='sectionID',
        ),
        migrations.AddField(
            model_name='question',
            name='courseID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courseListAPI.course'),
            preserve_default=False,
        ),
    ]
