# Generated by Django 5.0.2 on 2024-03-10 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseListAPI', '0005_course_coursedate_course_coursehours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='courseImage',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='course_images'),
        ),
    ]
