# Generated by Django 5.0.2 on 2024-03-13 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseListAPI', '0006_remove_question_questionanswer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isAnswer', models.BooleanField(default=False)),
                ('questionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courseListAPI.question')),
            ],
        ),
    ]
