# Generated by Django 5.0.2 on 2024-03-12 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseListAPI', '0008_alter_course_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='reviewText',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
