# Generated by Django 5.0.2 on 2024-03-12 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseListAPI', '0010_alter_course_reviews'),
        ('reviews', '0004_rename_coursereviewscore_studentreviewteacher_teacherreviewscore_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='reviews',
        ),
        migrations.AddField(
            model_name='course',
            name='reviews',
            field=models.ManyToManyField(related_name='studcoursereviews', to='reviews.studentreviewcourse'),
        ),
    ]
