# Generated by Django 5.0.2 on 2024-03-12 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courseListAPI', '0011_remove_course_reviews_course_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='reviewText',
        ),
    ]
