# Generated by Django 5.0.2 on 2024-03-14 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courseListAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment_Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courseListAPI.course')),
            ],
        ),
    ]
