# Generated by Django 4.2.10 on 2024-03-13 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payment_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment_course",
            name="courseName",
        ),
    ]
