# Generated by Django 5.0.2 on 2024-03-14 21:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0002_payment_course_paymentid_payment_course_user_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_course',
            name='courseDate',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
    ]
