# Generated by Django 5.0.2 on 2024-03-15 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0003_payment_course_coursedate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment_course',
            old_name='courseDate',
            new_name='paymentDate',
        ),
    ]
