# Generated by Django 5.0.2 on 2024-03-13 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_authentication_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="isApprove",
            field=models.BooleanField(default=False),
        ),
    ]
