# Generated by Django 5.0.2 on 2024-02-28 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_authentication_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
