# Generated by Django 5.0.2 on 2024-03-07 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
