# Generated by Django 5.0.2 on 2024-02-28 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_authentication_app", "0002_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phonenumber",
            field=models.IntegerField(null=True),
        ),
    ]
