# Generated by Django 5.0.2 on 2024-02-28 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_authentication_app", "0003_user_phonenumber"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="address",
            field=models.CharField(
                default="No address provided", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="classroom",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="educationstage",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="gradelevels",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="identificationcard",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="image",
            field=models.ImageField(null=True, upload_to="user_images/"),
        ),
        migrations.AddField(
            model_name="user",
            name="rating",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="usertype",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
