# Generated by Django 4.2.10 on 2024-02-28 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "user_authentication_app",
            "0004_user_address_user_classroom_user_educationstage_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="identificationcard",
            field=models.BigIntegerField(null=True),
        ),
    ]
