# Generated by Django 4.2.10 on 2024-02-28 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_authentication_app", "0005_alter_user_identificationcard"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="rating",
        ),
        migrations.AlterField(
            model_name="user",
            name="phonenumber",
            field=models.CharField(null=True),
        ),
    ]
