# Generated by Django 4.2.10 on 2024-02-28 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_authentication_app", "0006_remove_user_rating_alter_user_phonenumber"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="identificationcard",
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="image",
            field=models.ImageField(
                default="bk1.jfif", null=True, upload_to="user_images/"
            ),
        ),
    ]
