# Generated by Django 5.0.2 on 2024-03-11 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentreviewteacher',
            old_name='reviewRating',
            new_name='courseReviewScore',
        ),
    ]
