# Generated by Django 5.0.2 on 2024-03-18 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_initial'),
    ]

    operations = [
    ]
