# Generated by Django 5.0.2 on 2024-03-11 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_rename_reviewrating_studentreviewteacher_coursereviewscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentreviewteacher',
            name='courseReviewScore',
            field=models.FloatField(default=0),
        ),
    ]
