# Generated by Django 5.0.2 on 2024-03-11 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_studentreviewteacher_coursereviewscore'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentreviewteacher',
            old_name='courseReviewScore',
            new_name='teacherReviewScore',
        ),
        migrations.RemoveField(
            model_name='studentreviewcourse',
            name='reviewRating',
        ),
        migrations.AddField(
            model_name='studentreviewcourse',
            name='courseReviewScore',
            field=models.FloatField(default=0),
        ),
    ]
