# Generated by Django 5.0.2 on 2024-03-12 12:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_rename_coursereviewscore_studentreviewteacher_teacherreviewscore_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentreviewteacher',
            unique_together={('studentID', 'teacherID')},
        ),
    ]
