# Generated by Django 5.0.2 on 2024-03-13 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_alter_studentreviewteacher_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentreviewteacher',
            unique_together=set(),
        ),
    ]
