# Generated by Django 5.0.2 on 2024-03-15 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_studentreviewcourse_studentname'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentenrollsincourse',
            name='teacherID',
            field=models.IntegerField(default=0),
        ),
    ]
