# Generated by Django 5.0.2 on 2024-03-07 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('birthdate', models.DateField(null=True)),
                ('password', models.CharField(max_length=255)),
                ('classroom', models.CharField(max_length=255, null=True)),
                ('educationstage', models.CharField(choices=[('Pre-kindergarten', 'Prekindergarten'), ('Kindergarten', 'Kindergarten'), ('Elementary School', 'Elementaryschool'), ('High School', 'Highschool'), ('College', 'College'), ('Vocational Education Programs', 'Vocationaleducationprograms')], max_length=255, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phonenumber', models.CharField(null=True)),
                ('image', models.ImageField(default='bk1.jfif', null=True, upload_to='user_images/')),
                ('address', models.CharField(default='No address provided', max_length=255, null=True)),
            ],
        ),
    ]
